// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../packages/nuxt-module/src/runtime/plugin.client")> &
  InjectionType<typeof import("../../plugins/app-state.js")> &
  InjectionType<typeof import("../../plugins/app.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
