// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/llms/**:slug': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/llms/[...slug]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}