
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'DeferredDemo': typeof import("../components/demo/DeferredDemo.vue")['default']
    'DocApiSection': typeof import("../components/doc/DocApiSection.vue")['default']
    'DocApiTable': typeof import("../components/doc/DocApiTable.vue")['default']
    'DocComponent': typeof import("../components/doc/DocComponent.vue")['default']
    'DocCopyMarkdown': typeof import("../components/doc/DocCopyMarkdown.vue")['default']
    'DocPTViewer': typeof import("../components/doc/DocPTViewer.vue")['default']
    'DocSectionCode': typeof import("../components/doc/DocSectionCode.vue")['default']
    'DocSectionNav': typeof import("../components/doc/DocSectionNav.vue")['default']
    'DocSectionText': typeof import("../components/doc/DocSectionText.vue")['default']
    'DocSections': typeof import("../components/doc/DocSections.vue")['default']
    'DocStyledPreset': typeof import("../components/doc/DocStyledPreset.vue")['default']
    'Codeeditor': typeof import("../components/doc/codeeditor/index")['default']
    'Services': typeof import("../components/doc/codeeditor/services")['default']
    'Templates': typeof import("../components/doc/codeeditor/templates")['default']
    'Helpers': typeof import("../components/doc/helpers/index")['default']
    'BlockSection': typeof import("../components/landing/BlockSection.vue")['default']
    'FeaturesSection': typeof import("../components/landing/FeaturesSection.vue")['default']
    'FooterSection': typeof import("../components/landing/FooterSection.vue")['default']
    'HeroSection': typeof import("../components/landing/HeroSection.vue")['default']
    'TemplateSection': typeof import("../components/landing/TemplateSection.vue")['default']
    'ThemeSection': typeof import("../components/landing/ThemeSection.vue")['default']
    'UsersSection': typeof import("../components/landing/UsersSection.vue")['default']
    'CardsApp': typeof import("../components/landing/samples/CardsApp.vue")['default']
    'ChatApp': typeof import("../components/landing/samples/ChatApp.vue")['default']
    'CustomersApp': typeof import("../components/landing/samples/CustomersApp.vue")['default']
    'InboxApp': typeof import("../components/landing/samples/InboxApp.vue")['default']
    'MoviesApp': typeof import("../components/landing/samples/MoviesApp.vue")['default']
    'OverviewApp': typeof import("../components/landing/samples/OverviewApp.vue")['default']
    'AppConfigurator': typeof import("../components/layout/AppConfigurator.vue")['default']
    'AppDesigner': typeof import("../components/layout/AppDesigner.vue")['default']
    'AppFooter': typeof import("../components/layout/AppFooter.vue")['default']
    'AppMenu': typeof import("../components/layout/AppMenu.vue")['default']
    'AppMenuItem': typeof import("../components/layout/AppMenuItem.vue")['default']
    'AppNews': typeof import("../components/layout/AppNews.vue")['default']
    'AppTopBar': typeof import("../components/layout/AppTopBar.vue")['default']
    'PrimeVueNuxtLink': typeof import("../components/layout/PrimeVueNuxtLink")['default']
    'DesignCreateTheme': typeof import("../components/layout/designer/create/DesignCreateTheme.vue")['default']
    'DesignDashboard': typeof import("../components/layout/designer/dashboard/DesignDashboard.vue")['default']
    'DesignColorPalette': typeof import("../components/layout/designer/editor/DesignColorPalette.vue")['default']
    'DesignEditor': typeof import("../components/layout/designer/editor/DesignEditor.vue")['default']
    'DesignEditorFooter': typeof import("../components/layout/designer/editor/DesignEditorFooter.vue")['default']
    'DesignTokenField': typeof import("../components/layout/designer/editor/DesignTokenField.vue")['default']
    'DesignComponent': typeof import("../components/layout/designer/editor/component/DesignComponent.vue")['default']
    'DesignComponentSection': typeof import("../components/layout/designer/editor/component/DesignComponentSection.vue")['default']
    'DesignCustomTokens': typeof import("../components/layout/designer/editor/custom/DesignCustomTokens.vue")['default']
    'DesignBorderRadius': typeof import("../components/layout/designer/editor/primitive/DesignBorderRadius.vue")['default']
    'DesignColors': typeof import("../components/layout/designer/editor/primitive/DesignColors.vue")['default']
    'DesignSemantic': typeof import("../components/layout/designer/editor/semantic/DesignSemantic.vue")['default']
    'DesignSemanticSection': typeof import("../components/layout/designer/editor/semantic/DesignSemanticSection.vue")['default']
    'DesignSettings': typeof import("../components/layout/designer/editor/settings/DesignSettings.vue")['default']
    'TemplateConfiguration': typeof import("../components/template/TemplateConfiguration.vue")['default']
    'TemplateContainer': typeof import("../components/template/TemplateContainer.vue")['default']
    'TemplateFeatures': typeof import("../components/template/TemplateFeatures.vue")['default']
    'TemplateFeaturesAnimation': typeof import("../components/template/TemplateFeaturesAnimation.vue")['default']
    'TemplateFeaturesAnimationInline': typeof import("../components/template/TemplateFeaturesAnimationInline.vue")['default']
    'TemplateHero': typeof import("../components/template/TemplateHero.vue")['default']
    'TemplateLicense': typeof import("../components/template/TemplateLicense.vue")['default']
    'TemplateSeparator': typeof import("../components/template/TemplateSeparator.vue")['default']
    'ApolloLogo': typeof import("../components/template/logo/ApolloLogo.vue")['default']
    'AtlantisLogo': typeof import("../components/template/logo/AtlantisLogo.vue")['default']
    'AvalonLogo': typeof import("../components/template/logo/AvalonLogo.vue")['default']
    'DiamondLogo': typeof import("../components/template/logo/DiamondLogo.vue")['default']
    'FreyaLogo': typeof import("../components/template/logo/FreyaLogo.vue")['default']
    'GenesisLogo': typeof import("../components/template/logo/GenesisLogo.vue")['default']
    'PoseidonLogo': typeof import("../components/template/logo/PoseidonLogo.vue")['default']
    'SakaiLogo': typeof import("../components/template/logo/SakaiLogo.vue")['default']
    'UltimaLogo': typeof import("../components/template/logo/UltimaLogo.vue")['default']
    'VeronaLogo': typeof import("../components/template/logo/VeronaLogo.vue")['default']
    'ApolloSeparator': typeof import("../components/template/separator/ApolloSeparator.vue")['default']
    'AtlantisSeparator': typeof import("../components/template/separator/AtlantisSeparator.vue")['default']
    'AvalonSeparator': typeof import("../components/template/separator/AvalonSeparator.vue")['default']
    'DiamondSeparator': typeof import("../components/template/separator/DiamondSeparator.vue")['default']
    'FreyaSeparator': typeof import("../components/template/separator/FreyaSeparator.vue")['default']
    'GenesisSeparator': typeof import("../components/template/separator/GenesisSeparator.vue")['default']
    'PoseidonSeparator': typeof import("../components/template/separator/PoseidonSeparator.vue")['default']
    'SakaiSeparator': typeof import("../components/template/separator/SakaiSeparator.vue")['default']
    'UltimaSeparator': typeof import("../components/template/separator/UltimaSeparator.vue")['default']
    'VeronaSeparator': typeof import("../components/template/separator/VeronaSeparator.vue")['default']
    'NuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'AutoComplete': typeof import("primevue/autocomplete")['default']
    'Calendar': typeof import("primevue/calendar")['default']
    'CascadeSelect': typeof import("primevue/cascadeselect")['default']
    'Checkbox': typeof import("primevue/checkbox")['default']
    'CheckboxGroup': typeof import("primevue/checkboxgroup")['default']
    'Chips': typeof import("primevue/chips")['default']
    'ColorPicker': typeof import("primevue/colorpicker")['default']
    'DatePicker': typeof import("primevue/datepicker")['default']
    'Dropdown': typeof import("primevue/dropdown")['default']
    'FloatLabel': typeof import("primevue/floatlabel")['default']
    'Fluid': typeof import("primevue/fluid")['default']
    'IconField': typeof import("primevue/iconfield")['default']
    'IftaLabel': typeof import("primevue/iftalabel")['default']
    'InputChips': typeof import("primevue/inputchips")['default']
    'InputGroup': typeof import("primevue/inputgroup")['default']
    'InputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'InputIcon': typeof import("primevue/inputicon")['default']
    'InputMask': typeof import("primevue/inputmask")['default']
    'InputNumber': typeof import("primevue/inputnumber")['default']
    'InputOtp': typeof import("primevue/inputotp")['default']
    'InputSwitch': typeof import("primevue/inputswitch")['default']
    'InputText': typeof import("primevue/inputtext")['default']
    'Knob': typeof import("primevue/knob")['default']
    'Listbox': typeof import("primevue/listbox")['default']
    'MultiSelect': typeof import("primevue/multiselect")['default']
    'Password': typeof import("primevue/password")['default']
    'RadioButton': typeof import("primevue/radiobutton")['default']
    'RadioButtonGroup': typeof import("primevue/radiobuttongroup")['default']
    'Rating': typeof import("primevue/rating")['default']
    'Select': typeof import("primevue/select")['default']
    'SelectButton': typeof import("primevue/selectbutton")['default']
    'Slider': typeof import("primevue/slider")['default']
    'Textarea': typeof import("primevue/textarea")['default']
    'ToggleButton': typeof import("primevue/togglebutton")['default']
    'ToggleSwitch': typeof import("primevue/toggleswitch")['default']
    'TreeSelect': typeof import("primevue/treeselect")['default']
    'Button': typeof import("primevue/button")['default']
    'ButtonGroup': typeof import("primevue/buttongroup")['default']
    'SpeedDial': typeof import("primevue/speeddial")['default']
    'SplitButton': typeof import("primevue/splitbutton")['default']
    'Column': typeof import("primevue/column")['default']
    'Row': typeof import("primevue/row")['default']
    'ColumnGroup': typeof import("primevue/columngroup")['default']
    'DataTable': typeof import("primevue/datatable")['default']
    'DataView': typeof import("primevue/dataview")['default']
    'OrderList': typeof import("primevue/orderlist")['default']
    'OrganizationChart': typeof import("primevue/organizationchart")['default']
    'Paginator': typeof import("primevue/paginator")['default']
    'PickList': typeof import("primevue/picklist")['default']
    'Tree': typeof import("primevue/tree")['default']
    'TreeTable': typeof import("primevue/treetable")['default']
    'Timeline': typeof import("primevue/timeline")['default']
    'VirtualScroller': typeof import("primevue/virtualscroller")['default']
    'Accordion': typeof import("primevue/accordion")['default']
    'AccordionPanel': typeof import("primevue/accordionpanel")['default']
    'AccordionHeader': typeof import("primevue/accordionheader")['default']
    'AccordionContent': typeof import("primevue/accordioncontent")['default']
    'AccordionTab': typeof import("primevue/accordiontab")['default']
    'Card': typeof import("primevue/card")['default']
    'DeferredContent': typeof import("primevue/deferredcontent")['default']
    'Divider': typeof import("primevue/divider")['default']
    'Fieldset': typeof import("primevue/fieldset")['default']
    'Panel': typeof import("primevue/panel")['default']
    'ScrollPanel': typeof import("primevue/scrollpanel")['default']
    'Splitter': typeof import("primevue/splitter")['default']
    'SplitterPanel': typeof import("primevue/splitterpanel")['default']
    'Stepper': typeof import("primevue/stepper")['default']
    'StepList': typeof import("primevue/steplist")['default']
    'Step': typeof import("primevue/step")['default']
    'StepItem': typeof import("primevue/stepitem")['default']
    'StepPanels': typeof import("primevue/steppanels")['default']
    'StepPanel': typeof import("primevue/steppanel")['default']
    'TabView': typeof import("primevue/tabview")['default']
    'Tabs': typeof import("primevue/tabs")['default']
    'TabList': typeof import("primevue/tablist")['default']
    'Tab': typeof import("primevue/tab")['default']
    'TabPanels': typeof import("primevue/tabpanels")['default']
    'TabPanel': typeof import("primevue/tabpanel")['default']
    'Toolbar': typeof import("primevue/toolbar")['default']
    'ConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'ConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'Dialog': typeof import("primevue/dialog")['default']
    'Drawer': typeof import("primevue/drawer")['default']
    'DynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'OverlayPanel': typeof import("primevue/overlaypanel")['default']
    'Popover': typeof import("primevue/popover")['default']
    'Sidebar': typeof import("primevue/sidebar")['default']
    'FileUpload': typeof import("primevue/fileupload")['default']
    'Breadcrumb': typeof import("primevue/breadcrumb")['default']
    'ContextMenu': typeof import("primevue/contextmenu")['default']
    'Dock': typeof import("primevue/dock")['default']
    'Menu': typeof import("primevue/menu")['default']
    'Menubar': typeof import("primevue/menubar")['default']
    'MegaMenu': typeof import("primevue/megamenu")['default']
    'PanelMenu': typeof import("primevue/panelmenu")['default']
    'Steps': typeof import("primevue/steps")['default']
    'TabMenu': typeof import("primevue/tabmenu")['default']
    'TieredMenu': typeof import("primevue/tieredmenu")['default']
    'Message': typeof import("primevue/message")['default']
    'InlineMessage': typeof import("primevue/inlinemessage")['default']
    'Toast': typeof import("primevue/toast")['default']
    'Carousel': typeof import("primevue/carousel")['default']
    'Galleria': typeof import("primevue/galleria")['default']
    'Image': typeof import("primevue/image")['default']
    'ImageCompare': typeof import("primevue/imagecompare")['default']
    'Avatar': typeof import("primevue/avatar")['default']
    'AvatarGroup': typeof import("primevue/avatargroup")['default']
    'Badge': typeof import("primevue/badge")['default']
    'BlockUI': typeof import("primevue/blockui")['default']
    'Chip': typeof import("primevue/chip")['default']
    'Inplace': typeof import("primevue/inplace")['default']
    'MeterGroup': typeof import("primevue/metergroup")['default']
    'OverlayBadge': typeof import("primevue/overlaybadge")['default']
    'ScrollTop': typeof import("primevue/scrolltop")['default']
    'Skeleton': typeof import("primevue/skeleton")['default']
    'ProgressBar': typeof import("primevue/progressbar")['default']
    'ProgressSpinner': typeof import("primevue/progressspinner")['default']
    'Tag': typeof import("primevue/tag")['default']
    'Terminal': typeof import("primevue/terminal")['default']
    'Form': typeof import("@primevue/forms/form")['default']
    'FormField': typeof import("@primevue/forms/formfield")['default']
    'NuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyDeferredDemo': typeof import("../components/demo/DeferredDemo.vue")['default']
    'LazyDocApiSection': typeof import("../components/doc/DocApiSection.vue")['default']
    'LazyDocApiTable': typeof import("../components/doc/DocApiTable.vue")['default']
    'LazyDocComponent': typeof import("../components/doc/DocComponent.vue")['default']
    'LazyDocCopyMarkdown': typeof import("../components/doc/DocCopyMarkdown.vue")['default']
    'LazyDocPTViewer': typeof import("../components/doc/DocPTViewer.vue")['default']
    'LazyDocSectionCode': typeof import("../components/doc/DocSectionCode.vue")['default']
    'LazyDocSectionNav': typeof import("../components/doc/DocSectionNav.vue")['default']
    'LazyDocSectionText': typeof import("../components/doc/DocSectionText.vue")['default']
    'LazyDocSections': typeof import("../components/doc/DocSections.vue")['default']
    'LazyDocStyledPreset': typeof import("../components/doc/DocStyledPreset.vue")['default']
    'LazyCodeeditor': typeof import("../components/doc/codeeditor/index")['default']
    'LazyServices': typeof import("../components/doc/codeeditor/services")['default']
    'LazyTemplates': typeof import("../components/doc/codeeditor/templates")['default']
    'LazyHelpers': typeof import("../components/doc/helpers/index")['default']
    'LazyBlockSection': typeof import("../components/landing/BlockSection.vue")['default']
    'LazyFeaturesSection': typeof import("../components/landing/FeaturesSection.vue")['default']
    'LazyFooterSection': typeof import("../components/landing/FooterSection.vue")['default']
    'LazyHeroSection': typeof import("../components/landing/HeroSection.vue")['default']
    'LazyTemplateSection': typeof import("../components/landing/TemplateSection.vue")['default']
    'LazyThemeSection': typeof import("../components/landing/ThemeSection.vue")['default']
    'LazyUsersSection': typeof import("../components/landing/UsersSection.vue")['default']
    'LazyCardsApp': typeof import("../components/landing/samples/CardsApp.vue")['default']
    'LazyChatApp': typeof import("../components/landing/samples/ChatApp.vue")['default']
    'LazyCustomersApp': typeof import("../components/landing/samples/CustomersApp.vue")['default']
    'LazyInboxApp': typeof import("../components/landing/samples/InboxApp.vue")['default']
    'LazyMoviesApp': typeof import("../components/landing/samples/MoviesApp.vue")['default']
    'LazyOverviewApp': typeof import("../components/landing/samples/OverviewApp.vue")['default']
    'LazyAppConfigurator': typeof import("../components/layout/AppConfigurator.vue")['default']
    'LazyAppDesigner': typeof import("../components/layout/AppDesigner.vue")['default']
    'LazyAppFooter': typeof import("../components/layout/AppFooter.vue")['default']
    'LazyAppMenu': typeof import("../components/layout/AppMenu.vue")['default']
    'LazyAppMenuItem': typeof import("../components/layout/AppMenuItem.vue")['default']
    'LazyAppNews': typeof import("../components/layout/AppNews.vue")['default']
    'LazyAppTopBar': typeof import("../components/layout/AppTopBar.vue")['default']
    'LazyPrimeVueNuxtLink': typeof import("../components/layout/PrimeVueNuxtLink")['default']
    'LazyDesignCreateTheme': typeof import("../components/layout/designer/create/DesignCreateTheme.vue")['default']
    'LazyDesignDashboard': typeof import("../components/layout/designer/dashboard/DesignDashboard.vue")['default']
    'LazyDesignColorPalette': typeof import("../components/layout/designer/editor/DesignColorPalette.vue")['default']
    'LazyDesignEditor': typeof import("../components/layout/designer/editor/DesignEditor.vue")['default']
    'LazyDesignEditorFooter': typeof import("../components/layout/designer/editor/DesignEditorFooter.vue")['default']
    'LazyDesignTokenField': typeof import("../components/layout/designer/editor/DesignTokenField.vue")['default']
    'LazyDesignComponent': typeof import("../components/layout/designer/editor/component/DesignComponent.vue")['default']
    'LazyDesignComponentSection': typeof import("../components/layout/designer/editor/component/DesignComponentSection.vue")['default']
    'LazyDesignCustomTokens': typeof import("../components/layout/designer/editor/custom/DesignCustomTokens.vue")['default']
    'LazyDesignBorderRadius': typeof import("../components/layout/designer/editor/primitive/DesignBorderRadius.vue")['default']
    'LazyDesignColors': typeof import("../components/layout/designer/editor/primitive/DesignColors.vue")['default']
    'LazyDesignSemantic': typeof import("../components/layout/designer/editor/semantic/DesignSemantic.vue")['default']
    'LazyDesignSemanticSection': typeof import("../components/layout/designer/editor/semantic/DesignSemanticSection.vue")['default']
    'LazyDesignSettings': typeof import("../components/layout/designer/editor/settings/DesignSettings.vue")['default']
    'LazyTemplateConfiguration': typeof import("../components/template/TemplateConfiguration.vue")['default']
    'LazyTemplateContainer': typeof import("../components/template/TemplateContainer.vue")['default']
    'LazyTemplateFeatures': typeof import("../components/template/TemplateFeatures.vue")['default']
    'LazyTemplateFeaturesAnimation': typeof import("../components/template/TemplateFeaturesAnimation.vue")['default']
    'LazyTemplateFeaturesAnimationInline': typeof import("../components/template/TemplateFeaturesAnimationInline.vue")['default']
    'LazyTemplateHero': typeof import("../components/template/TemplateHero.vue")['default']
    'LazyTemplateLicense': typeof import("../components/template/TemplateLicense.vue")['default']
    'LazyTemplateSeparator': typeof import("../components/template/TemplateSeparator.vue")['default']
    'LazyApolloLogo': typeof import("../components/template/logo/ApolloLogo.vue")['default']
    'LazyAtlantisLogo': typeof import("../components/template/logo/AtlantisLogo.vue")['default']
    'LazyAvalonLogo': typeof import("../components/template/logo/AvalonLogo.vue")['default']
    'LazyDiamondLogo': typeof import("../components/template/logo/DiamondLogo.vue")['default']
    'LazyFreyaLogo': typeof import("../components/template/logo/FreyaLogo.vue")['default']
    'LazyGenesisLogo': typeof import("../components/template/logo/GenesisLogo.vue")['default']
    'LazyPoseidonLogo': typeof import("../components/template/logo/PoseidonLogo.vue")['default']
    'LazySakaiLogo': typeof import("../components/template/logo/SakaiLogo.vue")['default']
    'LazyUltimaLogo': typeof import("../components/template/logo/UltimaLogo.vue")['default']
    'LazyVeronaLogo': typeof import("../components/template/logo/VeronaLogo.vue")['default']
    'LazyApolloSeparator': typeof import("../components/template/separator/ApolloSeparator.vue")['default']
    'LazyAtlantisSeparator': typeof import("../components/template/separator/AtlantisSeparator.vue")['default']
    'LazyAvalonSeparator': typeof import("../components/template/separator/AvalonSeparator.vue")['default']
    'LazyDiamondSeparator': typeof import("../components/template/separator/DiamondSeparator.vue")['default']
    'LazyFreyaSeparator': typeof import("../components/template/separator/FreyaSeparator.vue")['default']
    'LazyGenesisSeparator': typeof import("../components/template/separator/GenesisSeparator.vue")['default']
    'LazyPoseidonSeparator': typeof import("../components/template/separator/PoseidonSeparator.vue")['default']
    'LazySakaiSeparator': typeof import("../components/template/separator/SakaiSeparator.vue")['default']
    'LazyUltimaSeparator': typeof import("../components/template/separator/UltimaSeparator.vue")['default']
    'LazyVeronaSeparator': typeof import("../components/template/separator/VeronaSeparator.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyAutoComplete': typeof import("primevue/autocomplete")['default']
    'LazyCalendar': typeof import("primevue/calendar")['default']
    'LazyCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'LazyCheckbox': typeof import("primevue/checkbox")['default']
    'LazyCheckboxGroup': typeof import("primevue/checkboxgroup")['default']
    'LazyChips': typeof import("primevue/chips")['default']
    'LazyColorPicker': typeof import("primevue/colorpicker")['default']
    'LazyDatePicker': typeof import("primevue/datepicker")['default']
    'LazyDropdown': typeof import("primevue/dropdown")['default']
    'LazyFloatLabel': typeof import("primevue/floatlabel")['default']
    'LazyFluid': typeof import("primevue/fluid")['default']
    'LazyIconField': typeof import("primevue/iconfield")['default']
    'LazyIftaLabel': typeof import("primevue/iftalabel")['default']
    'LazyInputChips': typeof import("primevue/inputchips")['default']
    'LazyInputGroup': typeof import("primevue/inputgroup")['default']
    'LazyInputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'LazyInputIcon': typeof import("primevue/inputicon")['default']
    'LazyInputMask': typeof import("primevue/inputmask")['default']
    'LazyInputNumber': typeof import("primevue/inputnumber")['default']
    'LazyInputOtp': typeof import("primevue/inputotp")['default']
    'LazyInputSwitch': typeof import("primevue/inputswitch")['default']
    'LazyInputText': typeof import("primevue/inputtext")['default']
    'LazyKnob': typeof import("primevue/knob")['default']
    'LazyListbox': typeof import("primevue/listbox")['default']
    'LazyMultiSelect': typeof import("primevue/multiselect")['default']
    'LazyPassword': typeof import("primevue/password")['default']
    'LazyRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyRadioButtonGroup': typeof import("primevue/radiobuttongroup")['default']
    'LazyRating': typeof import("primevue/rating")['default']
    'LazySelect': typeof import("primevue/select")['default']
    'LazySelectButton': typeof import("primevue/selectbutton")['default']
    'LazySlider': typeof import("primevue/slider")['default']
    'LazyTextarea': typeof import("primevue/textarea")['default']
    'LazyToggleButton': typeof import("primevue/togglebutton")['default']
    'LazyToggleSwitch': typeof import("primevue/toggleswitch")['default']
    'LazyTreeSelect': typeof import("primevue/treeselect")['default']
    'LazyButton': typeof import("primevue/button")['default']
    'LazyButtonGroup': typeof import("primevue/buttongroup")['default']
    'LazySpeedDial': typeof import("primevue/speeddial")['default']
    'LazySplitButton': typeof import("primevue/splitbutton")['default']
    'LazyColumn': typeof import("primevue/column")['default']
    'LazyRow': typeof import("primevue/row")['default']
    'LazyColumnGroup': typeof import("primevue/columngroup")['default']
    'LazyDataTable': typeof import("primevue/datatable")['default']
    'LazyDataView': typeof import("primevue/dataview")['default']
    'LazyOrderList': typeof import("primevue/orderlist")['default']
    'LazyOrganizationChart': typeof import("primevue/organizationchart")['default']
    'LazyPaginator': typeof import("primevue/paginator")['default']
    'LazyPickList': typeof import("primevue/picklist")['default']
    'LazyTree': typeof import("primevue/tree")['default']
    'LazyTreeTable': typeof import("primevue/treetable")['default']
    'LazyTimeline': typeof import("primevue/timeline")['default']
    'LazyVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'LazyAccordion': typeof import("primevue/accordion")['default']
    'LazyAccordionPanel': typeof import("primevue/accordionpanel")['default']
    'LazyAccordionHeader': typeof import("primevue/accordionheader")['default']
    'LazyAccordionContent': typeof import("primevue/accordioncontent")['default']
    'LazyAccordionTab': typeof import("primevue/accordiontab")['default']
    'LazyCard': typeof import("primevue/card")['default']
    'LazyDeferredContent': typeof import("primevue/deferredcontent")['default']
    'LazyDivider': typeof import("primevue/divider")['default']
    'LazyFieldset': typeof import("primevue/fieldset")['default']
    'LazyPanel': typeof import("primevue/panel")['default']
    'LazyScrollPanel': typeof import("primevue/scrollpanel")['default']
    'LazySplitter': typeof import("primevue/splitter")['default']
    'LazySplitterPanel': typeof import("primevue/splitterpanel")['default']
    'LazyStepper': typeof import("primevue/stepper")['default']
    'LazyStepList': typeof import("primevue/steplist")['default']
    'LazyStep': typeof import("primevue/step")['default']
    'LazyStepItem': typeof import("primevue/stepitem")['default']
    'LazyStepPanels': typeof import("primevue/steppanels")['default']
    'LazyStepPanel': typeof import("primevue/steppanel")['default']
    'LazyTabView': typeof import("primevue/tabview")['default']
    'LazyTabs': typeof import("primevue/tabs")['default']
    'LazyTabList': typeof import("primevue/tablist")['default']
    'LazyTab': typeof import("primevue/tab")['default']
    'LazyTabPanels': typeof import("primevue/tabpanels")['default']
    'LazyTabPanel': typeof import("primevue/tabpanel")['default']
    'LazyToolbar': typeof import("primevue/toolbar")['default']
    'LazyConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'LazyConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'LazyDialog': typeof import("primevue/dialog")['default']
    'LazyDrawer': typeof import("primevue/drawer")['default']
    'LazyDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'LazyOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'LazyPopover': typeof import("primevue/popover")['default']
    'LazySidebar': typeof import("primevue/sidebar")['default']
    'LazyFileUpload': typeof import("primevue/fileupload")['default']
    'LazyBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'LazyContextMenu': typeof import("primevue/contextmenu")['default']
    'LazyDock': typeof import("primevue/dock")['default']
    'LazyMenu': typeof import("primevue/menu")['default']
    'LazyMenubar': typeof import("primevue/menubar")['default']
    'LazyMegaMenu': typeof import("primevue/megamenu")['default']
    'LazyPanelMenu': typeof import("primevue/panelmenu")['default']
    'LazySteps': typeof import("primevue/steps")['default']
    'LazyTabMenu': typeof import("primevue/tabmenu")['default']
    'LazyTieredMenu': typeof import("primevue/tieredmenu")['default']
    'LazyMessage': typeof import("primevue/message")['default']
    'LazyInlineMessage': typeof import("primevue/inlinemessage")['default']
    'LazyToast': typeof import("primevue/toast")['default']
    'LazyCarousel': typeof import("primevue/carousel")['default']
    'LazyGalleria': typeof import("primevue/galleria")['default']
    'LazyImage': typeof import("primevue/image")['default']
    'LazyImageCompare': typeof import("primevue/imagecompare")['default']
    'LazyAvatar': typeof import("primevue/avatar")['default']
    'LazyAvatarGroup': typeof import("primevue/avatargroup")['default']
    'LazyBadge': typeof import("primevue/badge")['default']
    'LazyBlockUI': typeof import("primevue/blockui")['default']
    'LazyChip': typeof import("primevue/chip")['default']
    'LazyInplace': typeof import("primevue/inplace")['default']
    'LazyMeterGroup': typeof import("primevue/metergroup")['default']
    'LazyOverlayBadge': typeof import("primevue/overlaybadge")['default']
    'LazyScrollTop': typeof import("primevue/scrolltop")['default']
    'LazySkeleton': typeof import("primevue/skeleton")['default']
    'LazyProgressBar': typeof import("primevue/progressbar")['default']
    'LazyProgressSpinner': typeof import("primevue/progressspinner")['default']
    'LazyTag': typeof import("primevue/tag")['default']
    'LazyTerminal': typeof import("primevue/terminal")['default']
    'LazyForm': typeof import("@primevue/forms/form")['default']
    'LazyFormField': typeof import("@primevue/forms/formfield")['default']
    'LazyNuxtPage': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const DeferredDemo: typeof import("../components/demo/DeferredDemo.vue")['default']
export const DocApiSection: typeof import("../components/doc/DocApiSection.vue")['default']
export const DocApiTable: typeof import("../components/doc/DocApiTable.vue")['default']
export const DocComponent: typeof import("../components/doc/DocComponent.vue")['default']
export const DocCopyMarkdown: typeof import("../components/doc/DocCopyMarkdown.vue")['default']
export const DocPTViewer: typeof import("../components/doc/DocPTViewer.vue")['default']
export const DocSectionCode: typeof import("../components/doc/DocSectionCode.vue")['default']
export const DocSectionNav: typeof import("../components/doc/DocSectionNav.vue")['default']
export const DocSectionText: typeof import("../components/doc/DocSectionText.vue")['default']
export const DocSections: typeof import("../components/doc/DocSections.vue")['default']
export const DocStyledPreset: typeof import("../components/doc/DocStyledPreset.vue")['default']
export const Codeeditor: typeof import("../components/doc/codeeditor/index")['default']
export const Services: typeof import("../components/doc/codeeditor/services")['default']
export const Templates: typeof import("../components/doc/codeeditor/templates")['default']
export const Helpers: typeof import("../components/doc/helpers/index")['default']
export const BlockSection: typeof import("../components/landing/BlockSection.vue")['default']
export const FeaturesSection: typeof import("../components/landing/FeaturesSection.vue")['default']
export const FooterSection: typeof import("../components/landing/FooterSection.vue")['default']
export const HeroSection: typeof import("../components/landing/HeroSection.vue")['default']
export const TemplateSection: typeof import("../components/landing/TemplateSection.vue")['default']
export const ThemeSection: typeof import("../components/landing/ThemeSection.vue")['default']
export const UsersSection: typeof import("../components/landing/UsersSection.vue")['default']
export const CardsApp: typeof import("../components/landing/samples/CardsApp.vue")['default']
export const ChatApp: typeof import("../components/landing/samples/ChatApp.vue")['default']
export const CustomersApp: typeof import("../components/landing/samples/CustomersApp.vue")['default']
export const InboxApp: typeof import("../components/landing/samples/InboxApp.vue")['default']
export const MoviesApp: typeof import("../components/landing/samples/MoviesApp.vue")['default']
export const OverviewApp: typeof import("../components/landing/samples/OverviewApp.vue")['default']
export const AppConfigurator: typeof import("../components/layout/AppConfigurator.vue")['default']
export const AppDesigner: typeof import("../components/layout/AppDesigner.vue")['default']
export const AppFooter: typeof import("../components/layout/AppFooter.vue")['default']
export const AppMenu: typeof import("../components/layout/AppMenu.vue")['default']
export const AppMenuItem: typeof import("../components/layout/AppMenuItem.vue")['default']
export const AppNews: typeof import("../components/layout/AppNews.vue")['default']
export const AppTopBar: typeof import("../components/layout/AppTopBar.vue")['default']
export const PrimeVueNuxtLink: typeof import("../components/layout/PrimeVueNuxtLink")['default']
export const DesignCreateTheme: typeof import("../components/layout/designer/create/DesignCreateTheme.vue")['default']
export const DesignDashboard: typeof import("../components/layout/designer/dashboard/DesignDashboard.vue")['default']
export const DesignColorPalette: typeof import("../components/layout/designer/editor/DesignColorPalette.vue")['default']
export const DesignEditor: typeof import("../components/layout/designer/editor/DesignEditor.vue")['default']
export const DesignEditorFooter: typeof import("../components/layout/designer/editor/DesignEditorFooter.vue")['default']
export const DesignTokenField: typeof import("../components/layout/designer/editor/DesignTokenField.vue")['default']
export const DesignComponent: typeof import("../components/layout/designer/editor/component/DesignComponent.vue")['default']
export const DesignComponentSection: typeof import("../components/layout/designer/editor/component/DesignComponentSection.vue")['default']
export const DesignCustomTokens: typeof import("../components/layout/designer/editor/custom/DesignCustomTokens.vue")['default']
export const DesignBorderRadius: typeof import("../components/layout/designer/editor/primitive/DesignBorderRadius.vue")['default']
export const DesignColors: typeof import("../components/layout/designer/editor/primitive/DesignColors.vue")['default']
export const DesignSemantic: typeof import("../components/layout/designer/editor/semantic/DesignSemantic.vue")['default']
export const DesignSemanticSection: typeof import("../components/layout/designer/editor/semantic/DesignSemanticSection.vue")['default']
export const DesignSettings: typeof import("../components/layout/designer/editor/settings/DesignSettings.vue")['default']
export const TemplateConfiguration: typeof import("../components/template/TemplateConfiguration.vue")['default']
export const TemplateContainer: typeof import("../components/template/TemplateContainer.vue")['default']
export const TemplateFeatures: typeof import("../components/template/TemplateFeatures.vue")['default']
export const TemplateFeaturesAnimation: typeof import("../components/template/TemplateFeaturesAnimation.vue")['default']
export const TemplateFeaturesAnimationInline: typeof import("../components/template/TemplateFeaturesAnimationInline.vue")['default']
export const TemplateHero: typeof import("../components/template/TemplateHero.vue")['default']
export const TemplateLicense: typeof import("../components/template/TemplateLicense.vue")['default']
export const TemplateSeparator: typeof import("../components/template/TemplateSeparator.vue")['default']
export const ApolloLogo: typeof import("../components/template/logo/ApolloLogo.vue")['default']
export const AtlantisLogo: typeof import("../components/template/logo/AtlantisLogo.vue")['default']
export const AvalonLogo: typeof import("../components/template/logo/AvalonLogo.vue")['default']
export const DiamondLogo: typeof import("../components/template/logo/DiamondLogo.vue")['default']
export const FreyaLogo: typeof import("../components/template/logo/FreyaLogo.vue")['default']
export const GenesisLogo: typeof import("../components/template/logo/GenesisLogo.vue")['default']
export const PoseidonLogo: typeof import("../components/template/logo/PoseidonLogo.vue")['default']
export const SakaiLogo: typeof import("../components/template/logo/SakaiLogo.vue")['default']
export const UltimaLogo: typeof import("../components/template/logo/UltimaLogo.vue")['default']
export const VeronaLogo: typeof import("../components/template/logo/VeronaLogo.vue")['default']
export const ApolloSeparator: typeof import("../components/template/separator/ApolloSeparator.vue")['default']
export const AtlantisSeparator: typeof import("../components/template/separator/AtlantisSeparator.vue")['default']
export const AvalonSeparator: typeof import("../components/template/separator/AvalonSeparator.vue")['default']
export const DiamondSeparator: typeof import("../components/template/separator/DiamondSeparator.vue")['default']
export const FreyaSeparator: typeof import("../components/template/separator/FreyaSeparator.vue")['default']
export const GenesisSeparator: typeof import("../components/template/separator/GenesisSeparator.vue")['default']
export const PoseidonSeparator: typeof import("../components/template/separator/PoseidonSeparator.vue")['default']
export const SakaiSeparator: typeof import("../components/template/separator/SakaiSeparator.vue")['default']
export const UltimaSeparator: typeof import("../components/template/separator/UltimaSeparator.vue")['default']
export const VeronaSeparator: typeof import("../components/template/separator/VeronaSeparator.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AutoComplete: typeof import("primevue/autocomplete")['default']
export const Calendar: typeof import("primevue/calendar")['default']
export const CascadeSelect: typeof import("primevue/cascadeselect")['default']
export const Checkbox: typeof import("primevue/checkbox")['default']
export const CheckboxGroup: typeof import("primevue/checkboxgroup")['default']
export const Chips: typeof import("primevue/chips")['default']
export const ColorPicker: typeof import("primevue/colorpicker")['default']
export const DatePicker: typeof import("primevue/datepicker")['default']
export const Dropdown: typeof import("primevue/dropdown")['default']
export const FloatLabel: typeof import("primevue/floatlabel")['default']
export const Fluid: typeof import("primevue/fluid")['default']
export const IconField: typeof import("primevue/iconfield")['default']
export const IftaLabel: typeof import("primevue/iftalabel")['default']
export const InputChips: typeof import("primevue/inputchips")['default']
export const InputGroup: typeof import("primevue/inputgroup")['default']
export const InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const InputIcon: typeof import("primevue/inputicon")['default']
export const InputMask: typeof import("primevue/inputmask")['default']
export const InputNumber: typeof import("primevue/inputnumber")['default']
export const InputOtp: typeof import("primevue/inputotp")['default']
export const InputSwitch: typeof import("primevue/inputswitch")['default']
export const InputText: typeof import("primevue/inputtext")['default']
export const Knob: typeof import("primevue/knob")['default']
export const Listbox: typeof import("primevue/listbox")['default']
export const MultiSelect: typeof import("primevue/multiselect")['default']
export const Password: typeof import("primevue/password")['default']
export const RadioButton: typeof import("primevue/radiobutton")['default']
export const RadioButtonGroup: typeof import("primevue/radiobuttongroup")['default']
export const Rating: typeof import("primevue/rating")['default']
export const Select: typeof import("primevue/select")['default']
export const SelectButton: typeof import("primevue/selectbutton")['default']
export const Slider: typeof import("primevue/slider")['default']
export const Textarea: typeof import("primevue/textarea")['default']
export const ToggleButton: typeof import("primevue/togglebutton")['default']
export const ToggleSwitch: typeof import("primevue/toggleswitch")['default']
export const TreeSelect: typeof import("primevue/treeselect")['default']
export const Button: typeof import("primevue/button")['default']
export const ButtonGroup: typeof import("primevue/buttongroup")['default']
export const SpeedDial: typeof import("primevue/speeddial")['default']
export const SplitButton: typeof import("primevue/splitbutton")['default']
export const Column: typeof import("primevue/column")['default']
export const Row: typeof import("primevue/row")['default']
export const ColumnGroup: typeof import("primevue/columngroup")['default']
export const DataTable: typeof import("primevue/datatable")['default']
export const DataView: typeof import("primevue/dataview")['default']
export const OrderList: typeof import("primevue/orderlist")['default']
export const OrganizationChart: typeof import("primevue/organizationchart")['default']
export const Paginator: typeof import("primevue/paginator")['default']
export const PickList: typeof import("primevue/picklist")['default']
export const Tree: typeof import("primevue/tree")['default']
export const TreeTable: typeof import("primevue/treetable")['default']
export const Timeline: typeof import("primevue/timeline")['default']
export const VirtualScroller: typeof import("primevue/virtualscroller")['default']
export const Accordion: typeof import("primevue/accordion")['default']
export const AccordionPanel: typeof import("primevue/accordionpanel")['default']
export const AccordionHeader: typeof import("primevue/accordionheader")['default']
export const AccordionContent: typeof import("primevue/accordioncontent")['default']
export const AccordionTab: typeof import("primevue/accordiontab")['default']
export const Card: typeof import("primevue/card")['default']
export const DeferredContent: typeof import("primevue/deferredcontent")['default']
export const Divider: typeof import("primevue/divider")['default']
export const Fieldset: typeof import("primevue/fieldset")['default']
export const Panel: typeof import("primevue/panel")['default']
export const ScrollPanel: typeof import("primevue/scrollpanel")['default']
export const Splitter: typeof import("primevue/splitter")['default']
export const SplitterPanel: typeof import("primevue/splitterpanel")['default']
export const Stepper: typeof import("primevue/stepper")['default']
export const StepList: typeof import("primevue/steplist")['default']
export const Step: typeof import("primevue/step")['default']
export const StepItem: typeof import("primevue/stepitem")['default']
export const StepPanels: typeof import("primevue/steppanels")['default']
export const StepPanel: typeof import("primevue/steppanel")['default']
export const TabView: typeof import("primevue/tabview")['default']
export const Tabs: typeof import("primevue/tabs")['default']
export const TabList: typeof import("primevue/tablist")['default']
export const Tab: typeof import("primevue/tab")['default']
export const TabPanels: typeof import("primevue/tabpanels")['default']
export const TabPanel: typeof import("primevue/tabpanel")['default']
export const Toolbar: typeof import("primevue/toolbar")['default']
export const ConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const ConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const Dialog: typeof import("primevue/dialog")['default']
export const Drawer: typeof import("primevue/drawer")['default']
export const DynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const OverlayPanel: typeof import("primevue/overlaypanel")['default']
export const Popover: typeof import("primevue/popover")['default']
export const Sidebar: typeof import("primevue/sidebar")['default']
export const FileUpload: typeof import("primevue/fileupload")['default']
export const Breadcrumb: typeof import("primevue/breadcrumb")['default']
export const ContextMenu: typeof import("primevue/contextmenu")['default']
export const Dock: typeof import("primevue/dock")['default']
export const Menu: typeof import("primevue/menu")['default']
export const Menubar: typeof import("primevue/menubar")['default']
export const MegaMenu: typeof import("primevue/megamenu")['default']
export const PanelMenu: typeof import("primevue/panelmenu")['default']
export const Steps: typeof import("primevue/steps")['default']
export const TabMenu: typeof import("primevue/tabmenu")['default']
export const TieredMenu: typeof import("primevue/tieredmenu")['default']
export const Message: typeof import("primevue/message")['default']
export const InlineMessage: typeof import("primevue/inlinemessage")['default']
export const Toast: typeof import("primevue/toast")['default']
export const Carousel: typeof import("primevue/carousel")['default']
export const Galleria: typeof import("primevue/galleria")['default']
export const Image: typeof import("primevue/image")['default']
export const ImageCompare: typeof import("primevue/imagecompare")['default']
export const Avatar: typeof import("primevue/avatar")['default']
export const AvatarGroup: typeof import("primevue/avatargroup")['default']
export const Badge: typeof import("primevue/badge")['default']
export const BlockUI: typeof import("primevue/blockui")['default']
export const Chip: typeof import("primevue/chip")['default']
export const Inplace: typeof import("primevue/inplace")['default']
export const MeterGroup: typeof import("primevue/metergroup")['default']
export const OverlayBadge: typeof import("primevue/overlaybadge")['default']
export const ScrollTop: typeof import("primevue/scrolltop")['default']
export const Skeleton: typeof import("primevue/skeleton")['default']
export const ProgressBar: typeof import("primevue/progressbar")['default']
export const ProgressSpinner: typeof import("primevue/progressspinner")['default']
export const Tag: typeof import("primevue/tag")['default']
export const Terminal: typeof import("primevue/terminal")['default']
export const Form: typeof import("@primevue/forms/form")['default']
export const FormField: typeof import("@primevue/forms/formfield")['default']
export const NuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyDeferredDemo: typeof import("../components/demo/DeferredDemo.vue")['default']
export const LazyDocApiSection: typeof import("../components/doc/DocApiSection.vue")['default']
export const LazyDocApiTable: typeof import("../components/doc/DocApiTable.vue")['default']
export const LazyDocComponent: typeof import("../components/doc/DocComponent.vue")['default']
export const LazyDocCopyMarkdown: typeof import("../components/doc/DocCopyMarkdown.vue")['default']
export const LazyDocPTViewer: typeof import("../components/doc/DocPTViewer.vue")['default']
export const LazyDocSectionCode: typeof import("../components/doc/DocSectionCode.vue")['default']
export const LazyDocSectionNav: typeof import("../components/doc/DocSectionNav.vue")['default']
export const LazyDocSectionText: typeof import("../components/doc/DocSectionText.vue")['default']
export const LazyDocSections: typeof import("../components/doc/DocSections.vue")['default']
export const LazyDocStyledPreset: typeof import("../components/doc/DocStyledPreset.vue")['default']
export const LazyCodeeditor: typeof import("../components/doc/codeeditor/index")['default']
export const LazyServices: typeof import("../components/doc/codeeditor/services")['default']
export const LazyTemplates: typeof import("../components/doc/codeeditor/templates")['default']
export const LazyHelpers: typeof import("../components/doc/helpers/index")['default']
export const LazyBlockSection: typeof import("../components/landing/BlockSection.vue")['default']
export const LazyFeaturesSection: typeof import("../components/landing/FeaturesSection.vue")['default']
export const LazyFooterSection: typeof import("../components/landing/FooterSection.vue")['default']
export const LazyHeroSection: typeof import("../components/landing/HeroSection.vue")['default']
export const LazyTemplateSection: typeof import("../components/landing/TemplateSection.vue")['default']
export const LazyThemeSection: typeof import("../components/landing/ThemeSection.vue")['default']
export const LazyUsersSection: typeof import("../components/landing/UsersSection.vue")['default']
export const LazyCardsApp: typeof import("../components/landing/samples/CardsApp.vue")['default']
export const LazyChatApp: typeof import("../components/landing/samples/ChatApp.vue")['default']
export const LazyCustomersApp: typeof import("../components/landing/samples/CustomersApp.vue")['default']
export const LazyInboxApp: typeof import("../components/landing/samples/InboxApp.vue")['default']
export const LazyMoviesApp: typeof import("../components/landing/samples/MoviesApp.vue")['default']
export const LazyOverviewApp: typeof import("../components/landing/samples/OverviewApp.vue")['default']
export const LazyAppConfigurator: typeof import("../components/layout/AppConfigurator.vue")['default']
export const LazyAppDesigner: typeof import("../components/layout/AppDesigner.vue")['default']
export const LazyAppFooter: typeof import("../components/layout/AppFooter.vue")['default']
export const LazyAppMenu: typeof import("../components/layout/AppMenu.vue")['default']
export const LazyAppMenuItem: typeof import("../components/layout/AppMenuItem.vue")['default']
export const LazyAppNews: typeof import("../components/layout/AppNews.vue")['default']
export const LazyAppTopBar: typeof import("../components/layout/AppTopBar.vue")['default']
export const LazyPrimeVueNuxtLink: typeof import("../components/layout/PrimeVueNuxtLink")['default']
export const LazyDesignCreateTheme: typeof import("../components/layout/designer/create/DesignCreateTheme.vue")['default']
export const LazyDesignDashboard: typeof import("../components/layout/designer/dashboard/DesignDashboard.vue")['default']
export const LazyDesignColorPalette: typeof import("../components/layout/designer/editor/DesignColorPalette.vue")['default']
export const LazyDesignEditor: typeof import("../components/layout/designer/editor/DesignEditor.vue")['default']
export const LazyDesignEditorFooter: typeof import("../components/layout/designer/editor/DesignEditorFooter.vue")['default']
export const LazyDesignTokenField: typeof import("../components/layout/designer/editor/DesignTokenField.vue")['default']
export const LazyDesignComponent: typeof import("../components/layout/designer/editor/component/DesignComponent.vue")['default']
export const LazyDesignComponentSection: typeof import("../components/layout/designer/editor/component/DesignComponentSection.vue")['default']
export const LazyDesignCustomTokens: typeof import("../components/layout/designer/editor/custom/DesignCustomTokens.vue")['default']
export const LazyDesignBorderRadius: typeof import("../components/layout/designer/editor/primitive/DesignBorderRadius.vue")['default']
export const LazyDesignColors: typeof import("../components/layout/designer/editor/primitive/DesignColors.vue")['default']
export const LazyDesignSemantic: typeof import("../components/layout/designer/editor/semantic/DesignSemantic.vue")['default']
export const LazyDesignSemanticSection: typeof import("../components/layout/designer/editor/semantic/DesignSemanticSection.vue")['default']
export const LazyDesignSettings: typeof import("../components/layout/designer/editor/settings/DesignSettings.vue")['default']
export const LazyTemplateConfiguration: typeof import("../components/template/TemplateConfiguration.vue")['default']
export const LazyTemplateContainer: typeof import("../components/template/TemplateContainer.vue")['default']
export const LazyTemplateFeatures: typeof import("../components/template/TemplateFeatures.vue")['default']
export const LazyTemplateFeaturesAnimation: typeof import("../components/template/TemplateFeaturesAnimation.vue")['default']
export const LazyTemplateFeaturesAnimationInline: typeof import("../components/template/TemplateFeaturesAnimationInline.vue")['default']
export const LazyTemplateHero: typeof import("../components/template/TemplateHero.vue")['default']
export const LazyTemplateLicense: typeof import("../components/template/TemplateLicense.vue")['default']
export const LazyTemplateSeparator: typeof import("../components/template/TemplateSeparator.vue")['default']
export const LazyApolloLogo: typeof import("../components/template/logo/ApolloLogo.vue")['default']
export const LazyAtlantisLogo: typeof import("../components/template/logo/AtlantisLogo.vue")['default']
export const LazyAvalonLogo: typeof import("../components/template/logo/AvalonLogo.vue")['default']
export const LazyDiamondLogo: typeof import("../components/template/logo/DiamondLogo.vue")['default']
export const LazyFreyaLogo: typeof import("../components/template/logo/FreyaLogo.vue")['default']
export const LazyGenesisLogo: typeof import("../components/template/logo/GenesisLogo.vue")['default']
export const LazyPoseidonLogo: typeof import("../components/template/logo/PoseidonLogo.vue")['default']
export const LazySakaiLogo: typeof import("../components/template/logo/SakaiLogo.vue")['default']
export const LazyUltimaLogo: typeof import("../components/template/logo/UltimaLogo.vue")['default']
export const LazyVeronaLogo: typeof import("../components/template/logo/VeronaLogo.vue")['default']
export const LazyApolloSeparator: typeof import("../components/template/separator/ApolloSeparator.vue")['default']
export const LazyAtlantisSeparator: typeof import("../components/template/separator/AtlantisSeparator.vue")['default']
export const LazyAvalonSeparator: typeof import("../components/template/separator/AvalonSeparator.vue")['default']
export const LazyDiamondSeparator: typeof import("../components/template/separator/DiamondSeparator.vue")['default']
export const LazyFreyaSeparator: typeof import("../components/template/separator/FreyaSeparator.vue")['default']
export const LazyGenesisSeparator: typeof import("../components/template/separator/GenesisSeparator.vue")['default']
export const LazyPoseidonSeparator: typeof import("../components/template/separator/PoseidonSeparator.vue")['default']
export const LazySakaiSeparator: typeof import("../components/template/separator/SakaiSeparator.vue")['default']
export const LazyUltimaSeparator: typeof import("../components/template/separator/UltimaSeparator.vue")['default']
export const LazyVeronaSeparator: typeof import("../components/template/separator/VeronaSeparator.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyAutoComplete: typeof import("primevue/autocomplete")['default']
export const LazyCalendar: typeof import("primevue/calendar")['default']
export const LazyCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const LazyCheckbox: typeof import("primevue/checkbox")['default']
export const LazyCheckboxGroup: typeof import("primevue/checkboxgroup")['default']
export const LazyChips: typeof import("primevue/chips")['default']
export const LazyColorPicker: typeof import("primevue/colorpicker")['default']
export const LazyDatePicker: typeof import("primevue/datepicker")['default']
export const LazyDropdown: typeof import("primevue/dropdown")['default']
export const LazyFloatLabel: typeof import("primevue/floatlabel")['default']
export const LazyFluid: typeof import("primevue/fluid")['default']
export const LazyIconField: typeof import("primevue/iconfield")['default']
export const LazyIftaLabel: typeof import("primevue/iftalabel")['default']
export const LazyInputChips: typeof import("primevue/inputchips")['default']
export const LazyInputGroup: typeof import("primevue/inputgroup")['default']
export const LazyInputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const LazyInputIcon: typeof import("primevue/inputicon")['default']
export const LazyInputMask: typeof import("primevue/inputmask")['default']
export const LazyInputNumber: typeof import("primevue/inputnumber")['default']
export const LazyInputOtp: typeof import("primevue/inputotp")['default']
export const LazyInputSwitch: typeof import("primevue/inputswitch")['default']
export const LazyInputText: typeof import("primevue/inputtext")['default']
export const LazyKnob: typeof import("primevue/knob")['default']
export const LazyListbox: typeof import("primevue/listbox")['default']
export const LazyMultiSelect: typeof import("primevue/multiselect")['default']
export const LazyPassword: typeof import("primevue/password")['default']
export const LazyRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyRadioButtonGroup: typeof import("primevue/radiobuttongroup")['default']
export const LazyRating: typeof import("primevue/rating")['default']
export const LazySelect: typeof import("primevue/select")['default']
export const LazySelectButton: typeof import("primevue/selectbutton")['default']
export const LazySlider: typeof import("primevue/slider")['default']
export const LazyTextarea: typeof import("primevue/textarea")['default']
export const LazyToggleButton: typeof import("primevue/togglebutton")['default']
export const LazyToggleSwitch: typeof import("primevue/toggleswitch")['default']
export const LazyTreeSelect: typeof import("primevue/treeselect")['default']
export const LazyButton: typeof import("primevue/button")['default']
export const LazyButtonGroup: typeof import("primevue/buttongroup")['default']
export const LazySpeedDial: typeof import("primevue/speeddial")['default']
export const LazySplitButton: typeof import("primevue/splitbutton")['default']
export const LazyColumn: typeof import("primevue/column")['default']
export const LazyRow: typeof import("primevue/row")['default']
export const LazyColumnGroup: typeof import("primevue/columngroup")['default']
export const LazyDataTable: typeof import("primevue/datatable")['default']
export const LazyDataView: typeof import("primevue/dataview")['default']
export const LazyOrderList: typeof import("primevue/orderlist")['default']
export const LazyOrganizationChart: typeof import("primevue/organizationchart")['default']
export const LazyPaginator: typeof import("primevue/paginator")['default']
export const LazyPickList: typeof import("primevue/picklist")['default']
export const LazyTree: typeof import("primevue/tree")['default']
export const LazyTreeTable: typeof import("primevue/treetable")['default']
export const LazyTimeline: typeof import("primevue/timeline")['default']
export const LazyVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const LazyAccordion: typeof import("primevue/accordion")['default']
export const LazyAccordionPanel: typeof import("primevue/accordionpanel")['default']
export const LazyAccordionHeader: typeof import("primevue/accordionheader")['default']
export const LazyAccordionContent: typeof import("primevue/accordioncontent")['default']
export const LazyAccordionTab: typeof import("primevue/accordiontab")['default']
export const LazyCard: typeof import("primevue/card")['default']
export const LazyDeferredContent: typeof import("primevue/deferredcontent")['default']
export const LazyDivider: typeof import("primevue/divider")['default']
export const LazyFieldset: typeof import("primevue/fieldset")['default']
export const LazyPanel: typeof import("primevue/panel")['default']
export const LazyScrollPanel: typeof import("primevue/scrollpanel")['default']
export const LazySplitter: typeof import("primevue/splitter")['default']
export const LazySplitterPanel: typeof import("primevue/splitterpanel")['default']
export const LazyStepper: typeof import("primevue/stepper")['default']
export const LazyStepList: typeof import("primevue/steplist")['default']
export const LazyStep: typeof import("primevue/step")['default']
export const LazyStepItem: typeof import("primevue/stepitem")['default']
export const LazyStepPanels: typeof import("primevue/steppanels")['default']
export const LazyStepPanel: typeof import("primevue/steppanel")['default']
export const LazyTabView: typeof import("primevue/tabview")['default']
export const LazyTabs: typeof import("primevue/tabs")['default']
export const LazyTabList: typeof import("primevue/tablist")['default']
export const LazyTab: typeof import("primevue/tab")['default']
export const LazyTabPanels: typeof import("primevue/tabpanels")['default']
export const LazyTabPanel: typeof import("primevue/tabpanel")['default']
export const LazyToolbar: typeof import("primevue/toolbar")['default']
export const LazyConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const LazyConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const LazyDialog: typeof import("primevue/dialog")['default']
export const LazyDrawer: typeof import("primevue/drawer")['default']
export const LazyDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const LazyOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const LazyPopover: typeof import("primevue/popover")['default']
export const LazySidebar: typeof import("primevue/sidebar")['default']
export const LazyFileUpload: typeof import("primevue/fileupload")['default']
export const LazyBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const LazyContextMenu: typeof import("primevue/contextmenu")['default']
export const LazyDock: typeof import("primevue/dock")['default']
export const LazyMenu: typeof import("primevue/menu")['default']
export const LazyMenubar: typeof import("primevue/menubar")['default']
export const LazyMegaMenu: typeof import("primevue/megamenu")['default']
export const LazyPanelMenu: typeof import("primevue/panelmenu")['default']
export const LazySteps: typeof import("primevue/steps")['default']
export const LazyTabMenu: typeof import("primevue/tabmenu")['default']
export const LazyTieredMenu: typeof import("primevue/tieredmenu")['default']
export const LazyMessage: typeof import("primevue/message")['default']
export const LazyInlineMessage: typeof import("primevue/inlinemessage")['default']
export const LazyToast: typeof import("primevue/toast")['default']
export const LazyCarousel: typeof import("primevue/carousel")['default']
export const LazyGalleria: typeof import("primevue/galleria")['default']
export const LazyImage: typeof import("primevue/image")['default']
export const LazyImageCompare: typeof import("primevue/imagecompare")['default']
export const LazyAvatar: typeof import("primevue/avatar")['default']
export const LazyAvatarGroup: typeof import("primevue/avatargroup")['default']
export const LazyBadge: typeof import("primevue/badge")['default']
export const LazyBlockUI: typeof import("primevue/blockui")['default']
export const LazyChip: typeof import("primevue/chip")['default']
export const LazyInplace: typeof import("primevue/inplace")['default']
export const LazyMeterGroup: typeof import("primevue/metergroup")['default']
export const LazyOverlayBadge: typeof import("primevue/overlaybadge")['default']
export const LazyScrollTop: typeof import("primevue/scrolltop")['default']
export const LazySkeleton: typeof import("primevue/skeleton")['default']
export const LazyProgressBar: typeof import("primevue/progressbar")['default']
export const LazyProgressSpinner: typeof import("primevue/progressspinner")['default']
export const LazyTag: typeof import("primevue/tag")['default']
export const LazyTerminal: typeof import("primevue/terminal")['default']
export const LazyForm: typeof import("@primevue/forms/form")['default']
export const LazyFormField: typeof import("@primevue/forms/formfield")['default']
export const LazyNuxtPage: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/.pnpm/nuxt@3.15.4_@parcel+watcher@2.5.4_@types+node@25.5.0_cac@6.7.14_db0@0.3.4_eslint@9.39.2_jiti@_2dq2wxp6am7cat32tr7ehkx4va/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
